[package]
name = "fluct-consensus-single"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluct-core = { version = "0.1", path = "../../core" }
thiserror = "1.0.48"
ethers-core = "2.0.9"
