[package]
name = "deop-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
ethers-core = "2.0.9"
serde = { version = "1.0.188", features = ["derive"] }
